name: spectrum_example
description: Example usage of package:spectrum.
version: 0.1.0
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  spectrum:
    git:
      url: https://github.com/felixjunghans/spectrum.git
      ref: 81b77bdc745febe16a1c1f906a7e2e84fa93397c
  foil:
    path: ../../foil/

flutter:
  uses-material-design: true
